using namespace System

Set-StrictMode -Version Latest

###############################################################################
#
# BATTLE ACTION TYPE
#
# PHYSICAL
#    ATTACKS THAT DON'T HAVE A SPECIFIC ELEMENTAL AFFINITY.
#
# ELEMENTAL FIRE
#    ATTACKS THAT HAVE A FIRE-BASED ELEMENTAL AFFINITY.
#
# ELEMENTAL WATER
#    ATTACKS THAT HAVE A WATER-BASED ELEMENTAL AFFINITY.
#
# ELEMENTAL EARTH
#    ATTACKS THAT HAVE AN EARTH-BASED ELEMENTAL AFFINITY.
#
# ELEMENTAL WIND
#    ATTACKS THAT HAVE A WIND-BASED ELEMENTAL AFFINITY.
#
# ELEMENTAL LIGHT
#    ATTACKS THAT HAVE A HOLY-BASED ELEMENTAL AFFINITY.
#
# ELEMENTAL DARK
#    ATTACKS THAT HAVE A HELL-BASED ELEMENTAL AFFINITY.
#
# ELEMENTAL ICE
#    ATTACKS THAT HAVE A AN ICE-BASED ELEMENTAL AFFINITY.
#
# MAGIC POISON
#    ATTACKS THAT HAVE A CHANCE TO POISON THE ENEMY.
#
# MAGIC CONFUSE
#    ATTACKS THAT HAVE A CHANCE TO CONFUSE THE ENEMY.
#
# MAGIC SLEEP
#    ATTACKS THAT HAVE A CHANCE TO PUT THE ENEMY TO SLEEP.
#
# MAGIC AGING
#    ATTACKS THAT HAVE A CHANCE TO INFLICT AGING ON THE ENEMY.
#
# MAGIC HEALING
#    ATTACKS THAT CAN HEAL THE ENEMY OR PLAYER.
#
# MAGIC STAT AUGMENT
#    ATTACKS THAT CAN PROVIDE A TEMPORARY BUFF TO A SPECIFIC STAT.
#
# NONE
#    A PLACEHOLDER FOR BASE CASE EVALUATIONS.
#
###############################################################################

Enum BattleActionType {
    Physical
    ElementalFire
    ElementalWater
    ElementalEarth
    ElementalWind
    ElementalLight
    ElementalDark
    ElementalIce
    MagicPoison
    MagicConfuse
    MagicSleep
    MagicAging
    MagicHealing
    MagicStatAugment
    None
}
