using namespace System

Set-StrictMode -Version Latest

#//////////////////////////////////////////////////////////////////////////////
#
# BATTLE ACTION RESULT TYPE
#
# SUMMARIZES THE KINDS OF RESULTS THAT CAN OCCUR FROM EXECUTING A BATTLE ACTION.
#
# SUCCESS
#    THE ACTION WAS SUCCESSFULLY EXECUTED.
#
# SUCCESS WITH CRITICAL
#    THE ACTION WAS SUCCESSFULLY EXECUTED AND GAINED A CRITICAL BONUS.
#
# SUCCESSS WITH AFFINITY BONUS
#    THE ACTION WAS SUCCESSFULLY EXECUTED AND GAINED AN AFFINITY BONUS.
#
# SUCCESS WITH CRIT AND AFFINITY BONUS
#    THE ACTION WAS SUCCESSFULLY EXECUTED AND GAINED BOTH A CRITICAL AND AFFINITY BONUS.
#
# FAILED ATTACK MISSED
#    THE ACTION FAILED BECAUSE THE ATTACK MISSED.
#
# FAILED ATTACK FAILED
#    THE ACTION FAILED BECAUSE THE USER FAILED TO EXECUTE IT CORRECTLY.
#
# (DEPRECATED) FAILED NO USES REMAINING
#    THE ACTION FAILED BECAUSE THERE ARE NO REMAINING USES.
#
# FAILED NOT ENOUGH MP
#    THE ACTION FAILED BECUASE THE USER DOESN'T HAVE ENOUGH MP.
#
#//////////////////////////////////////////////////////////////////////////////

Enum BattleActionResultType {
    Success
    SuccessWithCritical
    SuccessWithAffinityBonus
    SuccessWithCritAndAffinityBonus
    FailedAttackMissed
    FailedAttackFailed
    FailedElementalMatch
    FailedNoUsesRemaining
    FailedNotEnoughMp
}
