using namespace System

Set-StrictMode -Version Latest

###############################################################################
#
# STATUS SCREEN STATE
#
# MAIN MENU
#     THE PLAYER CAN CONTROL THE CHEVRON OF THE MAIN MENU TO MOVE UP AND DOWN.
#
# STATUS
#     THE PLAYER CAN VIEW THEIR CURRENT STATUS. THIS IS A READ-ONLY VIEW.
#
# ITEMS
#     THE PLAYER CAN VIEW THEIR ITEMS. THE PLAYER CAN NAVIGATE THROUGH A
#     VERTICAL PAGING OF THEIR INVENTORY AND CAN INTERACT WITH THE ITEMS TO
#     EITHER USE OR DROP THEM.
#
# EQUIP
#     THE PLAYER CAN VIEW AND MANAGE THEIR EQUIPMENT. EQUIPMENT IS DIVIDED INTO
#     SLOTS: WEAPON, HELMET, ARMOR, PAULDRONS, GAUNTLETS, GREAVES, BOOTS, AND
#     JEWELRY. EACH PIECE CAN PROVIDE STAT BONUSES AND MAY HAVE STAT
#     REQUIREMENTS. EQUIPMENT IS RESTRICTED BY GENDER AND CAN BE PURCHASED OR
#     FOUND AS LOOT.
#
# MAGIC
#     THE PLAYER CAN VIEW AND MANAGE THEIR LEARNED MAGIC SPELLS OR ABILITIES.
#     SPELLS CAN BE EQUIPPED TO SHORTCUTS FOR QUICK ACCESS IN BATTLE. DETAILS
#     SUCH AS MP COST, ELEMENTAL TYPE, AND EFFECTS ARE DISPLAYED.
#
# SAVE
#     THE PLAYER CAN SAVE THEIR CURRENT GAME PROGRESS TO A FILE. THIS OPTION
#     PROMPTS FOR CONFIRMATION AND HANDLES SAVE SLOT SELECTION.
#
# QUIT
#     THE PLAYER CAN EXIT TO THE MAIN MENU OR CLOSE THE GAME. THIS OPTION
#     PROMPTS FOR CONFIRMATION TO PREVENT ACCIDENTAL LOSS OF PROGRESS.
#
###############################################################################

Enum StatusScreenState {
    Setup
    MainMenu
    Status
    Items
    Equip
    Magic
    Save
    Quit
}
