using namespace System

Set-StrictMode -Version Latest

#//////////////////////////////////////////////////////////////////////////////
#
# WINDOW BORDER PART DIRTY
#
# IN SPITE OF WINDOW BORDER PART, WINDOW BORDERS DON'T DRAW THEIR PARTS INDIVIDUALLY.
# RATHER, THEY'RE DRAWN AS FOUR PIECES, EACH PEICE BEING A COMPOSITION OF PARTS.
# SOME OF THE MOTIVATION BEHIND THIS IS SIMPLICITY IN RENDERING, OTHERWISE I'D NEED
# TO MAINTAIN THE COORDINATES OF THE FAR CORNERS WHICH ISN'T DESIRABLE, AND
# BECAUSE THE LEGACY CODE ALREADY RENDERED EACH FACE WITH NO ISSUES EVEN BEFORE
# CONVERTING THEM TO A COMPOSITION.
#
# THE ADDED BENEFIT OF USING THIS ENUMERATION IS THAT IT REMOVES A HANDFUL OF STATIC
# MEMBERS FROM EACH WINDOW CLASS.
#
#//////////////////////////////////////////////////////////////////////////////

Enum WindowBorderPartDirty {
    Top
    Bottom
    Left
    Right
}
